name: Build
on: 
  push:
    branches:
    - main
  workflow_dispatch:
  pull_request:
jobs:
  Build-and-Test-CDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npx cdk synth

